#!/bin/bash

echo "HEX string to C-array"

str=""

for string in "$@"
do
    str="Origin string: "
    for (( i = 0; i < ${#string};));
    do
        if [[ "$((${#string}%2))" != "0" && "$i" == "0" ]];
        then
            str=$str"0${string:i:1}"
            i=$i+1
        else
            str=$str"${string:i:2}"
            i=$i+2
        fi

    done
    echo $str
    
    str="Reversed string: "
    
    for (( i = 0; i < ${#string};));
    do
        if [[ "$((${#string}%2))" != "0" && "$i" == "0" ]];
        then
            str=$str"0${string:${#string} - i - 1:1}"
            i=$i+1
        else
            str=$str"${string:${#string} - i - 2:2}"
            i=$i+2
        fi

    done

    echo $str

    str=""

    for (( i = 0; i < ${#string};));
    do
        if [[ "$((${#string}%2))" != "0" && "$i" == "0" ]];
        then
            str=$str"0x0${string:i:1}, "
            i=$i+1
        else
            str=$str"0x${string:i:2}, "
            i=$i+2
        fi

    done
    echo $str

    echo "Reversed:"

    IFS=' '
    read -a strarr <<< "$str"
    str=""
    for (( i = ${#strarr[*]} + 1; i != 0; --i));
    do
        str=$str" "${strarr[$i-1]}
    done
    echo $str
done