#!/bin/bash

echo "Installing useful packages"

# Script Directory
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

apt-get update && apt-get upgrade -y

"$SCRIPT_DIR/package_check_and_install" git
"$SCRIPT_DIR/package_check_and_install" cmake
"$SCRIPT_DIR/package_check_and_install" build-essential # Meta-package pack for GNU C/C++

