#!/bin/bash

echo "Installing GOST engine for OpenSSL"

pckgs=( git cmake libssl-dev openssl pkg-config )

for package in ${pckgs[@]}
do
  REQUIRED_PKG="$package"
  PKG_OK=$(dpkg-query -W --showformat='${Status}\n' $REQUIRED_PKG|grep "install ok installed")
  echo Checking for $REQUIRED_PKG: $PKG_OK
  if [ "" = "$PKG_OK" ]; then
    echo "No $REQUIRED_PKG. Setting up $REQUIRED_PKG."
    sudo apt-get --yes install $REQUIRED_PKG
  fi
done

mkdir tmp

git clone --recursive -j8 https://github.com/gost-engine/engine tmp/engine

mkdir tmp/engine/build
cd tmp/engine/build

cmake -DCMAKE_BUILD_TYPE=Release -DOPENSSL_ROOT_DIR=$(openssl version -d | cut -d '"' -f 2) ..
cmake --build . --target install --config Release

cp bin/gost.so $(openssl version -e | cut -d '"' -f 2)

cat $(openssl version -d | cut -d '"' -f 2)/openssl.cnf | sed -e "s/openssl_conf = .*/openssl_conf = openssl_def/" > openssl.cnf
echo "
[openssl_def]
engines = engine_section

[engine_section]
gost = gost_section

[gost_section]
engine_id = gost
dynamic_path = $(openssl version -e | cut -d '"' -f 2)/gost.so
default_algorithms = ALL" >> openssl.cnf

mv openssl.cnf $(openssl version -d | cut -d '"' -f 2)/openssl.cnf

cd ../../..
rm -rf tmp